apiVersion: v1
kind: Namespace
metadata:
  name: zia
  labels:
    env: uat

---
apiVersion: v1
kind: LimitRange

metadata:
  name: syedlimitrange
  namespace: zia

spec:
  limits:
    - default:
       cpu: 50m
       memory: 100Mi

      type: Container
