apiVersion: apps/v1
kind: Deployment
metadata:
  name: syeddeployment
spec:
  replicas: 20
  minReadySeconds: 60
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      name: deployment
  template:
    metadata:
      name: testpod
      labels:
        name: deployment
    spec:
      containers:
        - name: syed
          image: centos
          command: ["/bin/bash", "-c", "while true; do echo centos 2-2  revision 4; sleep 5; done"]

