apiVersion: v1
kind: Pod
metadata:
  name: pod4
  namespace: qa
  labels:
    name: devops
spec:
  containers:
    - name: cont3
      image: nginx
      resources:
        requests:
          memory: 500Mi
          cpu: 0.2
