apiVersion: v1
kind: Pod
metadata:
  name: pod1-cm1-literal
  labels:
    course: devops
spec:
  containers:
    - name: c1-fromlitralcm
      image: nginx
      env:
        - name: va1 #inside container env variable search
          valueFrom:
             configMapKeyRef:
               name: cm1   # cm name
               key: course # key
